import "./globals.css";
import Footer from "@/components/modules/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
        <SpeedInsights />
      </body>
    </html>
  );
}
